### PR TITLE
CFG path contraction condition was removing entry blocks

### PR DESCRIPTION
**Pull request by macrologist**
Addresses #911 

Path contraction in the CFG construction was allowing for entry blocks to be removed, despite declaring such behavior to be illegal in the comment preceding that removal.

### CODE REVIEW

**Comment by macrologist** [comment]
Compiling 

```
DECLARE ro BIT
DECLARE shot_count INTEGER[1]

LABEL @START
SUB shot_count[0] 1
JUMP-UNLESS @END shot_count[0]
JUMP @START
LABEL @END
```

should emit something like

```

DECLARE ro BIT
DECLARE shot_count INTEGER

JUMP @START                             # Entering/exiting rewiring: (#(0 1 2 3 4 5 6 7) . #(0 1 2 3 4 5 6 7))
LABEL @END                              # Entering rewiring: #(0 1 2 3 4 5 6 7)
HALT                                    # Exiting rewiring: #(0 1 2 3 4 5 6 7)
LABEL @START                            # Entering rewiring: #(0 1 2 3 4 5 6 7)
MEASURE 0 ro[0]
SUB shot_count[0] 1
JUMP-WHEN @START shot_count[0]
JUMP @END                               # Exiting rewiring: #(0 1 2 3 4 5 6 7)
```

**Comment by macrologist** [comment]
bah hold on. RESETS are now generating a pointless jump-to-next-position sequence:

```
RESET

```

is becomming 

```
JUMP @RESET-3323                       
LABEL @RESET-3323                       
RESET
```

working on it.

**Comment by macrologist** [comment]
Should be good. Tests pass on my Mac

**Review by stylewarning — CHANGES_REQUESTED** [review]
Can we just add a couple tests for the previously failing cases?

**Comment by macrologist** [comment]
@stylewarning add tests to cover the inciting example and one other

**Review by stylewarning — APPROVED** [review]

**Pull request merged**
