### PR TITLE
[#712] Add Hasse Diagram dev tool for Quil logical-scheduler.

### PR DESCRIPTION
**Pull request by mhdavid-hrl**
This tool gives a way to get a Hasse diagram to help visualize the
logical scheduler created for a given quil program. The
diagram is in the form of a Graphviz source file, called a "dot file",
conventionally named with file type ending ".gv", which can in turn be
readily transformed into a graphics format for viewing using tools
standardly available in all modern operating environments.

This tool contributes two functions that can output the .gv file to
either a stream or a named file:

  write-hasse-for-quil - output a Hasse diagram for a quil program
  (optionally with a program, which may improve the output

  write-hasse-for-logical-scheduler - output a Hasse diagram for a
  quil program (deriving the logical schedule)

A handful of functions or accessors defined in logical-schedule.lisp
had their names exported via the quil.si package to support this tool.

Resolves: #712 "Print a logical-schedule as a Hasse diagram"

### CODE REVIEW

**Comment by mhdavid-hrl** [comment]
I see there is cl-quil test TEST-MEASURE-SEMANTICS is failing, and I'm able to reproduce it on my end. Therefore, I'm closing this until further notice.

**Comment by mhdavid-hrl** [comment]
I tried running the tests on master and even one commit back, and still get same failing cl-quil test TEST-MEASURE-SEMANTICS, with error message Invalid initialization argument: :AMPLITUDES
The backtrace shows it's somewhere in the bowels of make-density-qvm (defined in density-qvm.lisp).
Although I cannot thus far figure out what's going, since the commits in this PR do not seem to have any bearing on this test failing, I'll open the PR again for now.
Can anyone @kilimanjaro @stylewarning @notmgsk figure out what's going on?

**Comment by mhdavid-hrl** [comment]
Update re error in TEST-MEASURE-SEMANTICS build: when I build with older version of QVM (the one Quicklisp fetches for me), it does not get the error. I found the up-to-date version of QVM's qvm:make-density-qvm function now passes along any old keyword you give it as args to make-instance on QVM:DENSITY-QVM.  That's because of a fairly recent commit (de95ead "density-qvm: provide missing kwargs to DENSITY-QVM") by @notmgsk. It's recent-ish -- but quite some time ago, Jan 2021.  Did something just now or very recently cause that version of QVM to be incorporated into these regression tests?

Now, this test function has been passing in unknown keyword :AMPLITUDES since many moons ago. Here's the code: (from: quilc: tests/misc-tests.lisp)
```
(defun %make-density-qvm-initialized-in-basis (num-qubits basis-index)
  "Make a DENSITY-QVM that is initialized in the basis state described by BASIS-INDEX.

To put the density matrix into the basis state, e.g., |01><11|, we would choose BASIS-INDEX = 7. In general, the basis state |a><b| is prepared by choosing BASIS-INDEX = (2^N * a + b)."
  (let ((amps (make-array (expt 2 (* 2 num-qubits))
                          :element-type 'qvm:cflonum
                          :initial-element (qvm:cflonum 0))))
    (setf (aref amps basis-index) (qvm:cflonum 1))
    (qvm:make-density-qvm num-qubits :amplitudes amps)))
```
But it seems it was being ignored silently, whereas now it's getting passed in, and that results in the immediate error.  
The forward-trace from the test function is as follows: (leaving out package prefixes)
```
test-measure-semantics 
  -> %test-measure-semantics 
  -> %make-density-qvm-initialized-in-basis 
  -> make-density-qvm
```
So this seems completely unrelated to the changes in this PR. I'm still not sure what all caused this bug only now to appear in a test run for this particular PR.  To figure that out will require more digging.

**Comment by mhdavid-hrl** [comment]
Here is an example of using this:
In Lisp:
```
(asdf:test-system :cl-quil/tools)
```
That loads this tool and some useful test code and runs regression tests.
Then try creating a Hasse diagram for a simple program:
```
(tools:write-hasse-for-quil "X 0; H 3; CNOT 0 1; X 3; CNOT 1 3" :output-file "e1.gv")
; => "/Users/mhdavid/e1.gv"
```
That produced a GraphViz dot file with the following contents:
```
digraph G {
    rankdir=BT;
    "X 3 [4]" -> "H 3 [5]"
    "CNOT 1 3 [3]" -> "X 3 [4]"
    "CNOT 1 3 [3]" -> "CNOT 0 1 [1]"
    "CNOT 0 1 [1]" -> "X 0 [2]"
}

# X 0; H 3; CNOT 0 1; X 3; CNOT 1 3
```
Notice that the quil program code, if available, appears below the graphviz code as a comment, just as a convenience.

Now in the shell, you can convert that file to, say, a PNG image file with this command:
```
dot -Tpng /Users/mhdavid/e1.gv -o e1.png
```
Now, you can view the new image file ("e1.png") in some image browsing tool. On MacOS, e.g., you can just do `open e1.png` to invoke the default image viewer on the file.
Here's the resulting image.
e1

Notice that each node's label text consists of the text of the instruction plus a certain unique integer in square brackets, like [1], [5], etc. These label integers have to be added to the node to make them unique.  Not sure that's the best approach. The issue is discussed in a comment in the source file of the hasse stuff.

**Comment by mhdavid-hrl** [comment]
Here's another example quil program with an example of generating Hasse diagram and corresponding image:
```
(tools:write-hasse-for-quil 
 '("DECLARE ro BIT[3]"
   "X 0"
   "X 2"
   "X 3"
   "SWAP 0 1"
   "SWAP 0 2"
   "MEASURE 0 ro[0]"
   "MEASURE 1 ro[1]"
   "MEASURE 2 ro[2]")
 :output-file "e2.gv")
; => "/Users/mhdavid/e2.gv"
```
Image:
e2

**Comment by notmgsk** [comment]
You can fake duplicate nodes by setting duplicates to have the same label: https://graphviz.org/faq/#FaqDupNode

**Comment by mhdavid-hrl** [comment]
> You can fake duplicate nodes by setting duplicates to have the same label: https://graphviz.org/faq/#FaqDupNode

Thank you -- that's really good.  There should be no issue with that, no information lost vs. the current approach.  Each node is guaranteed to correspond to a unique instruction instance.  And the label integer was not telling you much of anything, like the line number. (It was a randomish artifact of the graph search order.). OK, good, I want to make that change.

**Comment by mhdavid-hrl** [comment]
Following implementing the labelling improvement, based on Mark S's advice, here are revised diagrams for the above two examples.

```
X 0; H 3; CNOT 0 1; X 3; CNOT 1 3
```
e1

```
DECLARE ro BIT[3]
X 0
X 2
X 3
SWAP 0 1
SWAP 0 2
MEASURE 0 ro[0]
MEASURE 1 ro[1]
MEASURE 2 ro[2]
```
e2

**Comment by mhdavid-hrl** [comment]
Update: the CI failure was cleared thanks to PR https://github.com/quil-lang/quilc/pull/724, which makes the version of QVM match nicely. To take advantage of it, I had to rebase on master to get the relevant commit (dd4377f [#712] Add Hasse Diagram dev tool for Quil logical-scheduler.) Then I forced it up to this PR's branch. So that's where we are, but still want feedback and/or approval on this PR from all interested parties, especially approvers like @notmgsk and @stylewarning

**Review by kilimanjaro — DISMISSED** [review]
This looks good to me.

**Comment by mhdavid-hrl** [comment]
Update on recent changes to this PR: 3 recent pushes:
(1) rebased on master then forced push; 
(2) squashed original commit and fixup commit discussed above then forced push; and
(3) added readme for cl-quil.tools, comprising just the Hasse stuff for now.
Reviewers: please have a look. @stylewarning @kilimanjaro @notmgsk 
New readme can be viewed here: https://github.com/mhdavid-hrl/quilc/tree/712-feature/lsched-hasse-diagram/src/tools

**Comment by mhdavid-hrl** [comment]
(just squashed into a single commit, hopefully in preparation for merge)

**Review by notmgsk — APPROVED** [review]

**Pull request merged**
